src: methods.CNNAEU3.CNNAEU3
params:
  default:
    epochs: 200
    lr: 0.005
    lr1: !!float 3e-4
    lr2: !!float 1e-3
    lr3: !!float 5e-2
    lr4: !!float 1e-3
    batch_size: 20
    patch_size: 40
    num_patches: 200
    lambda1: !!float 1e-2
    lambda2: !!float 1
    lambda3: !!float 1e-3
    weight_decay: !!float 5e-5
    dp: 0.5

  JasperRidge:
    epochs: 320
    lr: 0.005
    lr1: !!float 3e-4
    lr2: !!float 1e-3
    lr3: !!float 5e-2
    lr4: !!float 1e-3
    batch_size: 20
    patch_size: 40
    num_patches: 250
    lambda1: !!float 1e-2
    lambda2: !!float 1
    lambda3: !!float 1e-3
    weight_decay: !!float 5e-5
    dp: 0.5

  Samson:
    epochs: 200
    lr: 0.005
    lr1: !!float 3e-4
    lr2: !!float 1e-3
    lr3: !!float 5e-2
    lr4: !!float 1e-3
    batch_size: 20
    patch_size: 40
    num_patches: 200
    lambda1: !!float 1e-2
    lambda2: !!float 1
    lambda3: !!float 1e-3
    weight_decay: !!float 5e-5
    dp: 0.5

  Urban4:
    epochs: 320
    lr: 0.005
    lr1: !!float 3e-4
    lr2: !!float 1e-3
    lr3: !!float 5e-2
    lr4: !!float 1e-3
    batch_size: 20
    patch_size: 40
    num_patches: 250
    lambda1: !!float 1e-2
    lambda2: !!float 1
    lambda3: !!float 1e-3
    weight_decay: !!float 5e-5
    dp: 0.5
