src: methods.CyCU4.CyCU4
params:
  default:
    LR: !!float 2e-3
    lr1: !!float 16e-4
    lr2: !!float 5.0e-07
    batch_size: 1
    EPOCH: 200
    beta: 0.5
    delta: !!float 1e-3
    gamma: !!float 1e-7
    sparse_decay: !!float 5e-6
    weight_decay_param: !!float 1e-4
    step_size: 15
    turns: 1

  Samson:
    EPOCH: 200
    LR: 0.0016
    batch_size: 1
    beta: 0.5
    delta: 0.01
    gamma: !!float 1.0e-07
    lr1: !!float 1e-7
    lr2: !!float 5.0e-07
    lr3: !!float 1
    lr4: !!float 1
    sparse_decay: !!float 5.0e-06
    step_size: 15
    turns: 1
    weight_decay_param: 0.0001

  JasperRidge:
    LR: !!float 8e-3
    lr1: !!float 1e-1
    batch_size: 1
    EPOCH: 480
    beta: 0.5
    delta: !!float 1e-2
    gamma: !!float 1e-7
    sparse_decay: 0
    weight_decay_param: 0