src: methods.EGU.EGU
params:
  default:
    EPOCH: 200
    lr: 0.01
    reg: 0.001
    weight_decay: !!float 1e-5

  JasperRidge:
    EPOCH: 300
    lr: !!float 1e-3
    reg: 0.001
    weight_decay: !!float 1e-5