src: methods.PGMSU3.PGMSU3
params:
  default:
    lr: !!float 1e-3
    epochs: 300
    z_dim: 4
    seed: 0
    lambda_kl: 0.001
    lambda_sad: 4
    lambda_vol: 6
    lambda_vca: 0.1

  JasperRidge:
    lr: !!float 5e-3
    epochs: 300
    z_dim: 4
    seed: 0
    lambda_kl: 0.5
    lambda_sad: 3
    lambda_vol: 7
    lambda_vca: 0.1

  DeepGUn_ex2:
    lr: !!float 1e-3
    epochs: 300
    z_dim: 4
    seed: 0
    weight_decay: !!float 1e-3
    lambda_kl: 0.5
    lambda_sad: 0.5
    lambda_vol: 0.5
    lambda_vca: 0.1

  DeepGUn_ex4:
    lr: !!float 1e-3
    epochs: 300
    z_dim: 4
    seed: 0
    lambda_kl: 0.5
    lambda_sad: 0.1
    lambda_vol: 1
    lambda_vca: 0.1

