src: methods.PGMSU2.PGMSU2
params:
  default:
    lr: !!float 1e-3
    epochs: 200
    z_dim: 4
    seed: 0
    lambda_kl: 0.001
    lambda_sad: 4
    lambda_vol: 6

  JasperRidge:
    lr: !!float 5e-3
    epochs: 200
    z_dim: 4
    seed: 0
    lambda_kl: 0.5
    lambda_sad: 3
    lambda_vol: 7

  DeepGUn_ex2:
    lr: !!float 1e-3
    epochs: 200
    z_dim: 4
    seed: 0
    weight_decay: !!float 1e-3
    lambda_kl: 0.5
    lambda_sad: 0.5
    lambda_vol: 0.5

  DeepGUn_ex4:
    lr: !!float 1e-3
    epochs: 320
    z_dim: 4
    seed: 0
    lambda_kl: 0.5
    lambda_sad: 0.1
    lambda_vol: 1

  Urban4:
    lr: !!float 1e-3
    epochs: 200
    z_dim: 4
    seed: 0
    lambda_kl: 0.001
    lambda_sad: 4
    lambda_vol: 6

  Urban5:
    lr: !!float 1e-3
    epochs: 200
    z_dim: 4
    seed: 0
    lambda_kl: 0.001
    lambda_sad: 4
    lambda_vol: 6

  Urban6:
    lr: !!float 1e-3
    epochs: 200
    z_dim: 4
    seed: 0
    lambda_kl: 0.001
    lambda_sad: 4
    lambda_vol: 6
