src: methods.VQVAE.VQVAE
params:
  default:
    EPOCH: 300
    lr: 0.001
    weight_decay: !!float 1e-5
    pretrain:
      lr: 0.001
      EPOCH: 4000

  JasperRidge:
    EPOCH: 200
    lr: 0.1

    weight_decay: !!float 1e-5
    pretrain:
      lr: 0.001
      EPOCH: 400