from custom_types import HsiDataset, HsiData, DatasetsEnum, InitA_Enum, InitE_Enum, MainCfg, HsiPropertyEnum

''' core.func '''

def extract_edm(y, a): ...

def sort_Edm_And_Abu(dtrue: HsiDataset, dpred: HsiDataset, case: int = 2, repeat: bool = False,
                     edm_repeat: bool = False, abu_repeat: bool = False,
                     tip: bool = False): ...


def __get_similarity_matrix(true_, pred_, P, similarity_func, tip=None): ...


def __choose_similarity_max(similarity_matrix, P, repeat, tip=None): ...


def __choose_similarity_min(similarity_matrix, P, repeat, tip=None): ...


def __sort_framework(true_, pred_, P, func, repeat): ...


def sort_edm(dtrue, dpred, P, func=None, repeat=False): ...


def sort_abu(dtrue, dpred, P, func=None, repeat=False): ...


''' core.load '''


def loadhsi(case: str) -> HsiDataset: ...


def loadInitData(dataset_name: str, init_str: str): ...


class ModuleLoader:
    @staticmethod
    def get_Metrics_Function(way: str): ...

    @staticmethod
    def get_Draw_Function(way: str): ...

    @staticmethod
    def get_Init_Function(way: str): ...

    @staticmethod
    def get_Method(method_name: str): ...

    @staticmethod
    def get_Method_params(dataset_name: str, method_name: str) -> dict: ...


''' core '''


class DataProcessor:
    @staticmethod
    def loadDatast(case: DatasetsEnum) -> HsiDataset: ...

    @staticmethod
    def set_seed(seed: int = 0): ...

    @classmethod
    def gen_initData(cls, data: HsiDataset, initE: InitE_Enum, initA: InitA_Enum, initD: int = None,
                     snr: float = 0, normalization: bool = True, seed: int = 0) -> HsiDataset: ...

    @staticmethod
    def gen_endmembers(Y_init: HsiData, dataset: HsiDataset, initE: InitE_Enum, seed=0) -> HsiData: ...

    @staticmethod
    def gen_abundances(Y_init: HsiData, E_init: HsiData, dataset: HsiDataset, initA: InitA_Enum,
                       seed=0) -> HsiData: ...

    @staticmethod
    def addNoise(data: HsiData, snr: float) -> HsiData: ...

    @staticmethod
    def norm(data, normalization=True) -> HsiData: ...

    @staticmethod
    def gen_Y(e, a): ...

    @staticmethod
    def sort_edm(dtrue: HsiData, dpred: HsiData, P, func=None, repeat: bool = False): ...

    @staticmethod
    def sort_abu(dtrue: HsiData, dpred: HsiData, P, func=None, repeat: bool = False): ...

    @staticmethod
    def sort_edm_and_abu(dtrue: HsiDataset, dpred: HsiDataset, case: int = 2,
                         repeat: bool = False, edm_repeat: bool = False,
                         abu_repeat: bool = False, tip: bool = False): ...

    @classmethod
    def oneClickProc(cls, data: HsiData, snr=0, normalization=True) -> HsiData: ...

    @staticmethod
    def getInitData(dataset_name: str, init_str: str): ...


class ModeAdapter:
    def __init__(self, cfg: MainCfg): ...

    def set_seed(self, seed: int = 0): ...

    def __getInitStr(self) -> str: ...

    def get_Dataset(self) -> HsiDataset: ...

    def get_InitData(self, dataset: HsiDataset, replace=False) -> HsiDataset: ...

    def get_Model(self): ...

    def get_params(self) -> dict: ...

    @staticmethod
    def run(method, params: dict, init: HsiDataset, savepath=None, output_display=True) -> HsiDataset: ...

    def get_Params_adjust(self): ...

    @staticmethod
    def sort_EndmembersAndAbundances(dataset: HsiDataset, datapred: HsiDataset) -> HsiDataset: ...

    def compute(self, dataset, datapred, out_path=None): ...

    def draw(self, dataset, datapred, out_path=None): ...


class MyLog:
    def __init__(self, cfg: MainCfg): ...

    def __genOutDir(self) -> str: ...

    def get_outdir(self): ...

    @classmethod
    def __dict_recursive(cls, dictionary, indent=0): ...

    def record(self, out_path): ...

    @staticmethod
    def record_inyaml(content, outpath): ...


class SmartMetrics:
    def __init__(self, dataset: HsiDataset, tip=True) -> None: ...

    def compute_RMSE(self, A_true, A_pred): ...

    def compute_RMSE_2(self, A_true, A_pred): ...

    def compute_RMSE_a2(self, A_true, A_pred):
        if A_true.shape != A_pred.shape: ...

    def compute_SAD_3D(self, data_true, data_pred): ...

    def compute_SAD(self, E_true, E_pred, prop: HsiPropertyEnum = HsiPropertyEnum.E): ...

    def compute_SRE(self, A_true, A_pred): ...
