 ex1:
  datasets: "JasperRidge"
  methods: [ "ELMM", "GLMM", "PLMM", "MESMA", "DeepGUn", "PGMSU", "DGASU" ],
  edm_name:
    JasperRidge: [ "Tree", "Water", "Soil", "Road" ],
    DeepGUn_ex2: [ "EM #1", "EM #2", "EM #3" ]
  default:
    obj_file: 'results.mat',  #
    src: '/res',
    dst: '/_exp/ex2',
    draw: '_abus1',  #
    xlsx: False,  #